[versions]
kotlin = "2.2.20"
rdGen = "2025.1.1"
riderSdk = "2026.1-EAP5-SNAPSHOT"
riderSdkPreview = "2026.1-EAP5-SNAPSHOT"

[libraries]
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
rdGen = { group = "com.jetbrains.rd", name = "rd-gen", version.ref = "rdGen" }

[plugins]
changelog = "org.jetbrains.changelog:2.4.0"
gradleIntelliJPlatform = "org.jetbrains.intellij.platform:2.6.0"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.15.0"
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
