[versions]
kotlin = "2.0.20"
rdGen = "2024.1.1"
riderSdk = "2024.2.5"

[libraries]
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
rdGen = { group = "com.jetbrains.rd", name = "rd-gen", version.ref = "rdGen" }

[plugins]
changelog = "org.jetbrains.changelog:2.2.1"
gradleIntelliJPlatform = "org.jetbrains.intellij.platform:2.1.0"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.14.0"
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
